version: '3.1'
services:
  web:
    image: debiki/ed-web:$VERSION_TAG
    restart: always
    volumes:
      - ./conf/web/server-listen-http.conf:/etc/nginx/server-listen.conf:ro
      - ./conf/web/default-site/:/etc/nginx/default-site/:ro
      - ./data/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./data/certbot/:/etc/certbot/:ro
      - ./data/certbot-challenges/.well-known/:/opt/nginx/html/.well-known/:ro
      - ./data/uploads/:/opt/ed/uploads/:ro
      # Mount here so standard monitoring tools looking for Nginx logs will work.
      - /var/log/nginx/:/var/log/nginx/
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    # SECURITY COULD drop capabilities, see: http://rhelblog.redhat.com/2016/10/17/secure-your-containers-with-this-one-weird-trick/
    # Ask at Hacker News: which caps can I drop for an Nginx container? A JVM appserver?
    # Asked here about Nginx:
    #   https://stackoverflow.com/questions/43467670/which-capabilities-can-i-drop-in-a-docker-nginx-container
    # For all containers, not just 'web'.
    #cap_drop:
    #  - DAC_OVERRIDE
    #  ... many more?

  app:
    image: debiki/ed-app:$VERSION_TAG
    restart: always
    stdin_open: true  # otherwise Play Framework exits
    volumes:
      - ./conf/app/:/opt/ed/app-conf/:ro
      - ./data/uploads/:/opt/ed/uploads/
      # So backups can be downloaded via the admin web interface. But read-only,
      # so evil bugs cannot destroy all backups.
      - /opt/ed-backup/archives/:/opt/ed/backup-archives/:ro
      # Mount here so log monitoring agents like fluentd can access the log.
      - /var/log/ed/:/var/log/ed/
    links:
      - cache
      - rdb
      - search
    environment:
      CONFIG_FILE: /opt/ed/app-conf/play.conf
      POSTGRES_PASSWORD: '$POSTGRES_PASSWORD'

  cache:
    image: debiki/ed-cache:$VERSION_TAG
    restart: always
    volumes:
      - ./data/cache/:/data/
      - /var/log/redis/:/var/log/redis/
    sysctls:
      net.core.somaxconn: 511

  rdb:
    image: debiki/ed-rdb:$VERSION_TAG
    restart: always
    volumes:
      - ./data/rdb/:/var/lib/postgresql/data/
      # Mount here so standard monitoring tools configured to find Postgres logs here will work.
      # (Inside the container, we don't mount in /var/lib/postgresql/data/pg_log/ because
      # then Postgres would refuse to create a db in data/, because data/ wouldn't be empty.)
      - /var/log/postgresql/:/var/log/postgresql/
    environment:
      POSTGRES_PASSWORD: '$POSTGRES_PASSWORD'
      # Optionally, streaming replication peer:
      # (but you'll need to rename ./postgres-data/recovery.conf.disabled first — and
      # that file isn't created until you start Postgres)
      # PEER_HOST: 'postgres2'
      # PEER_PORT: '5432'
      # PEER_PASSWORD: '...'

  search:
    image: debiki/ed-search:$VERSION_TAG
    restart: always
    volumes:
      # COULD_OPTIMIZE Maybe use a Docker volume contanier here instead? What does the docs mean when
      # they say "Always use a volume bound on /usr/share/elasticsearch/data" — is mapping
      # a directory from the OS okay then? (that's using (parts of) a host's device/volume.
      # https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html#docker-cli-run-prod-mode
      - ./data/search/:/usr/share/elasticsearch/data/
      - ./data/search-logs/:/usr/share/elasticsearch/logs/
    ports:
      - '9200:9200'
      - '9300:9300'
    # If too low, the 'search' container will suddenly exit with code 137. No error message
    # will get logged — instead it just exits, suddenly. Why? OOM-killed? In Docker? Hmm.
    #mem_limit: 800M
    environment:
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  # (Do this later?)
  # This is a tiny web server to which one POSTs /make-cert?domain=www.example.com
  # and which then calls Bash & certbot. The resulting cert is mounted :ro in Nginx, above.
  # Or not a web server? Could be just some Bash scripts that looks at a /secure-hosts file that
  # the 'app' container updates, and the Bash scripts then creates Let's Encrypt certs for those hosts?
  # Bash scripts = simpler than a web server + API?
  #certbot:
  #  image: debiki/ed-certbot:$VERSION_TAG
  #  command: certbot-server
  #  restart: always
  #  volumes:
  #    - ./data/certbot/:/etc/certbot/
  #    - ./data/certbot-challenges/.well-known/:/opt/webserver/html/.well-known/
  #
  # todo:
  #   docker-compose run --rm certbot certbot ...  ?

# vim: et ts=2 sw=2
